LICENSE.md, examples/linux/rpmsg-echo-test/Makefile, examples/linux/rpmsg-echo-test/README, examples/linux/rpmsg-echo-test/echo_test.c
rpmsg-echo-test example demonstrates how to write linux userspace application that uses rpmsg devices in kernel space. This application sends pre-defined payload to remote processor firmware and waits for remote processor to send same payload back. It then verifies received payload integrity. Number of packets to send to remote processor can be configured from command line
Signed-off-by: Tanmay Shah <tanmay.shah@amd.com>
=> Add rpmsg-echo-test example

examples/linux/rpmsg-mat-mul/Makefile, examples/linux/rpmsg-mat-mul/README, examples/linux/rpmsg-mat-mul/mat_mul_demo.c, examples/linux/rpmsg-proxy-app/Makefile, examples/linux/rpmsg-proxy-app/README, examples/linux/rpmsg-proxy-app/proxy_app.c, examples/linux/rpmsg-proxy-app/proxy_app.h
rpmsg-mat-mul
This example demonstrates communication between host and remote processor
using rpmsg in kernelspace
rpmsg-proxy-app
This example demonstrates use of host file system by remote processor
Signed-off-by: Tanmay Shah <tanmay.shah@amd.com>
=> examples: add apps that uses rpmsg in kernelspace

examples/linux/rpmsg-proxy-app/proxy_app.c
rpmsg_dev_name string needed to find correct rpmsg_char device. This is required for the linux kernel >= 6.0.
Signed-off-by: Tanmay Shah <tanmay.shah@amd.com>
Fixes: 32e714cd73b5d5b7b71a4bfe94a5d92e0cf456f6
=> examples: rpmsg-proxy-app: fix rpmsg char dev path

examples/linux/rpmsg-echo-test/README.md, examples/linux/rpmsg-mat-mul/README.md, examples/linux/rpmsg-proxy-app/README.md
Current README.md contains many titles with # prefix of each line. It generates lots of indexes when these README files are linked in openamp-docs repo.
Remove redundant # prefix. Only keep it for demo title, compilation steps and demo run steps. This way, openamp-docs generates minimal index in table of content.
Also re-edit README.md files for better presentation.
Signed-off-by: Tanmay Shah <tanmay.shah@amd.com>
=> examples: Modify README formatting

examples/linux/rpmsg-echo-test/README.md, examples/linux/rpmsg-echo-test/echo_test.c, examples/linux/rpmsg-mat-mul/README.md, examples/linux/rpmsg-mat-mul/mat_mul_demo.c, examples/linux/rpmsg-proxy-app/README.md, examples/linux/rpmsg-proxy-app/proxy_app.c
As rpmsg_char driver will still be in use by rpmsg_ctrl, update to remove drivers in correct order to remove error:
'modprobe: FATAL: Module rpmsg_char is in use.'
Signed-off-by: Ben Levinsky <ben.levinsky@amd.com>
=> examples: rpmsg-proxy-app: Update drivers being removed

examples/linux/common/common.c, examples/linux/common/common.h, examples/linux/rpmsg-echo-test/Makefile, examples/linux/rpmsg-echo-test/echo_test.c, examples/linux/rpmsg-mat-mul/Makefile, examples/linux/rpmsg-mat-mul/mat_mul_demo.c, examples/linux/rpmsg-proxy-app/Makefile, examples/linux/rpmsg-proxy-app/proxy_app.c
This helps make these example files shorter and less intimidating for new users. Useful when trying to showcase OpenAMP to new users and teams.
=> Refactor example code

examples/linux/rpmsg-utils/README
Fix typo in the documentation.
=> examples: Linux: Fix rpmsg-utils README

examples/zephyr/rpmsg_multi_services/boards/qemu_cortex_r5.overlay, examples/zephyr/rpmsg_multi_services/src/sample.yaml
Add dt overlay with zephyr,ipc and zephyr,ipc_shm nodes for AMD-xilinx zynqmp platform.
This PR depends on and should be merged after Zephy IPM driver PR: https://github.com/zephyrproject-rtos/zephyr/pull/61008
=> examples: zephyr: add qemu_cortex_r5 board support

examples/zephyr/rpmsg_multi_services/boards/kv260_r5.overlay, examples/zephyr/rpmsg_multi_services/src/sample.yaml
Add dt overlay with zephyr,ipc and zephyr,ipc_shm nodes for AMD-xilinx zynqmp based kv260 board.
=> examples: zephyr: add kv260_r5 board support

examples/zephyr/dual_qemu_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.c
@uLipe @arnopo @tnmysh Hi. This is a trivial change that will help when testing the `dual_qemu_ivshmem`  example with the remote side running on a cortex-m machine with the QEMU ivshmem-flat device (no PCI, WIP). Could you please review it?
Thank you,
Cheers
=> examples: dual_qemu_ivshmem: Print shmem address and size

.readthedocs.yaml
The Readthedocs pull-request integration is nice to have for PR review. So run the whole OpenAMP-docs build but use the PR's commit
This also requires a ReadTheDocs project to install its integration for this repo. The project should enable "Build pull request for this project". It is currently in the Advanced Settings panel.
The project will also run for the main branch but that should be ignored and only the main project URL should be shown outside of PRs.
To this end the sub-module project names will use "-prs" in the name.
=> Docs: enable readthedocs rendering (for PRs)

west.yml
Prototype stage only.
TODO:
DONE: modify to work on Windows also
DONE: Get rid of wam remote stuff
WIP will be a different PR: Add CI github action workflow
=> Support building zephyr with upstream open-amp and libmetal

examples/zephyr/rpmsg_multi_services/boards/kv260_r5.overlay, examples/zephyr/rpmsg_multi_services/boards/qemu_cortex_r5.overlay, examples/zephyr/rpmsg_multi_services/boards/zynqmp_r5_override.dtsi
We are currently using Zephyr v3.5.0.
The memory definitions for kv260_r5 are inappropriate for general usage and for ours.
The current flash definition refers to the QSPI XIP area of the zynqmp. This is unlikely to be appropriate to use in the general case.  The current usage also assume use at offset 0 in the QSPI which is even less likely to be appropriate.  It is OK zynqmp_r5 to define this (perhaps with the name of qspi-xip) but it should not be selected as the default for flash. Let people that needs this opt into it.
For now we disable the zephyr,flash choice.  This does not eliminate the memory report line but it at least shows a region size of 0.
Likewise for the definition of RAM.  Zynqmp_r5 defines 64MB of RAM starting at offset 0.  This would be a mix of TCM and DDR depending …
=> zephyr: fixup kv260_r5 DT memory until it can be fixed in Zephyr

examples/linux/dts/xilinx/.gitignore, examples/linux/dts/xilinx/Makefile, examples/linux/dts/xilinx/kria-openamp-lockstep.dts, examples/linux/dts/xilinx/kria-openamp-split.dts, examples/linux/dts/xilinx/xilinx-openamp-for-v6.5.dtso, examples/linux/dts/xilinx/zcu102-openamp-base.dtsi, examples/linux/dts/xilinx/zcu102-openamp-lockstep.dts, examples/linux/dts/xilinx/zcu102-openamp-split.dts, examples/linux/dts/xilinx/zcu102-openamp.dtso, examples/linux/dts/xilinx/zynqmp-openamp.dtso, examples/linux/dts/xilinx/zynqmp-split.dtsi, examples/linux/dts/xilinx/zynqmp-split.dtso
- Switch to all overlays
- Add a compatible DTB for Xilinx bare-metal demos
- Fix the mailbox config for split mode (not used yet)
=> Several fixes for Zynqmp DTB

examples/linux/dts/st/.gitignore, examples/linux/dts/st/Makefile, examples/linux/dts/st/README.md, examples/linux/dts/st/st-audio-disable.dtso, examples/linux/dts/xilinx/.gitignore, examples/linux/dts/xilinx/Makefile, examples/linux/dts/xilinx/kria-openamp-lockstep.dts, examples/linux/dts/xilinx/kria-openamp-split.dts, examples/linux/dts/xilinx/xilinx-openamp-for-v6.5.dtso, examples/linux/dts/xilinx/zcu102-openamp-base.dtsi, examples/linux/dts/xilinx/zcu102-openamp-lockstep.dts, examples/linux/dts/xilinx/zcu102-openamp-split.dts, examples/linux/dts/xilinx/zcu102-openamp.dtso, examples/linux/dts/xilinx/zynqmp-openamp.dtso, examples/linux/dts/xilinx/zynqmp-split.dtsi, examples/linux/dts/xilinx/zynqmp-split.dtso
These DTB fixes came after the v2023.10.0 tag and we will not move that tag.
However this fixes are needed fro the v2023.10 demo images so we include them here.
The Zynqmp changes are already on main and are cherry picked back to this branch.
The ST audio disable workaround is only for this branch as hopefully it will not be needed in the future.
* Move zynqmp to all overlays (away from dtsi files)
* Add DTBO and DTBs for R5 bare-metal demos from Xilinx 2023.2
* Fix the mailbox config for zynqmp split mode (not used yet)
* Disable all audio devices in ST to avoid kernel oops in v6.5.8
* Fix the move to overlays for ZCU102
=> DTB fixes for v2023.10 release branch

examples/linux/dts/xilinx/zcu102-openamp.dtso
This fix is already in the v2023.10 branch but it is needed here on main as well.
A holdover from the dtsi model was getting both mailbox configs in the bare-metal dtb for zcu102.
Fix this by making the zcu102-openamp overlay only disable the serial port and not include the zynqmp-openamp overlay defs.
=> dtb: Fix zcu102 bare-metal

examples/zephyr/rpmsg_multi_services/README.rst
The rpmsg_char restructuring series is upstreamed since Linux kernel 5.18. Update the README in consequence
=> examples: zephyr: rpmsg multi service: update documentation

examples/linux/dts/xilinx/Makefile, examples/linux/dts/xilinx/xilinx-openamp-for-v6.x.dtso, examples/linux/dts/xilinx/zynqmp-openamp.dtso
No real update was needed for v6.6 but update the names and comments to make things more clear.  Delete the #if 0 stuff in the bare-metal dtso.
Looking ahead this configuration looks compatible and still needed for v6.6 through at least v6.10 (as of v6.10-rc6).
=> Zynqmp DTS: Update for v6.6 kernel

examples/linux/rpmsg-echo-test/echo_test.c, examples/linux/rpmsg-mat-mul/mat_mul_demo.c
Adding option -c for passing the rpmsg control device which the application needs to use.
Signe-off-by: Rajiv Mohan <rajiv.mohan@amd.com>
=> examples: linux: cmdline support for rpmsg ctrl dev

examples/linux/common/common.c
Fix linux apps and unbind rpmsg device with driver after rpmsg communication is done.
=> Unbind rpmsg dev

examples/zephyr/rpmsg_multi_services/README.rst
Update README file to include NXP i.MX8M Plus board support.
=> examples: Zephyr: update rpmsg-multi-service readme

examples/legacy_apps/tests/msg/rpmsg-nocopy-echo.c
The buff_list contains MAX_NB_TX_BUFF elements. 
The last element is at index (MAX_NB_TX_BUFF - 1).
=> legay_apps: test: fix bad array index in  rpmsg-nocopy-echo

examples/legacy_apps/examples/rpc_demo/CMakeLists.txt
Add the missing -fPIC option for dynamic library generation to fix the following error:
/usr/bin/ld: CMakeFiles/rpc_demod-shared.dir/__/__/system/linux/machine/generic/rsc_table.c.o: relocation R_X86_64_PC32 against symbol `resources' can not be used when making a shared object; recompile with -fPIC
=> legacy_apps: Fix rpc demo dynamic library build

.readthedocs-conf.py, .readthedocs.yaml
Upstream Read The Docs has tightened up the schema checking and this broke what we were doing for PRs.
A good number of things were tried but the best compromise is to:
* supply a dummy sphinx config file in this repo
* override the default build command to use the openamp-docs dir
Also:
* add more documentation about what is going on
* lock to html only format.  PRs only do html anyway but make sure
=> docs: update the readthedocs integration for PRs in this repo

examples/legacy_apps/CMakeLists.txt
We currently support an old version of CMake (3.0.2) that was released in 2018. Next cmake revisions will support 3.5 as minimum version.
Update the minimum version to 3.16, aligned with the libmetal and the open-amp libraies.
By updating to CMake 3.16 as the minimum version, we can also clean up the following policy add-ons:
- CMP0048 added in CMake v3.0
- CMP0077 added in CMake v3.13
=> legacy apps: update cmake minimum support to 3.16

examples/legacy_apps/examples/linux_rpc_demo/linux_rpc_demod.c, examples/legacy_apps/examples/load_fw/platform_info.c, examples/legacy_apps/examples/load_fw/zynqmp_apu_lcm_rproc_example.c, examples/legacy_apps/examples/load_fw/zynqmp_rpu_lcm_rproc_example.c, examples/legacy_apps/examples/rpc_demo/rpc_demod.c, examples/legacy_apps/machine/microblaze_generic/platform_info.c, examples/legacy_apps/machine/zynq7/platform_info.c, examples/legacy_apps/machine/zynq7/platform_info_remoteproc_master.c, examples/legacy_apps/machine/zynq7/zynq_a9_rproc.c, examples/legacy_apps/machine/zynqmp/platform_info.c, examples/legacy_apps/machine/zynqmp/zynqmp_linux_r5_proc.c, examples/legacy_apps/machine/zynqmp_r5/platform_info.c, examples/legacy_apps/machine/zynqmp_r5/zynqmp_r5_a53_rproc.c, examples/legacy_apps/system/generic/machine/zynq7/helper.c, examples/legacy_apps/system/generic/machine/zynqmp_r5/helper.c, examples/legacy_apps/system/linux/machine/generic/platform_info.c, examples/linux/common/common.c, examples/linux/rpmsg-proxy-app/proxy_app.c
Replace spaces with tabulations and update the formatting of some comments.
=> examples: fix indentation and comments

examples/linux/dts/xilinx/xilinx-openamp-for-v6.x.dtso, examples/linux/dts/xilinx/zynqmp-openamp.dtso
Linux 6.12 kernel has updated node name for r5 cores. Fix example dts accordingly otherwise it will generate wrong dt example that won't work.
=> linux: dts: xlnx: Fix r5f node name as per 6.12 kernel

examples/linux/dts/xilinx/Makefile, examples/linux/dts/xilinx/xilinx-openamp-for-v6.x.dtso, examples/linux/dts/xilinx/zynqmp-lockstep.dtso, examples/linux/dts/xilinx/zynqmp-openamp.dtso
Use new remoteproc nodes introduced in 6.12 kernel.
=> examples: dts: xlnx: update dtso for remoteproc nodes

examples/legacy_apps/machine/zynqmp_r5/helper.c, examples/legacy_apps/machine/zynqmp_r5/linker_large_text.ld, examples/legacy_apps/machine/zynqmp_r5/linker_remote.ld, examples/legacy_apps/machine/zynqmp_r5/platform_info.c, examples/legacy_apps/machine/zynqmp_r5/rsc_table.c, examples/legacy_apps/machine/zynqmp_r5/rsc_table.h
This PR adds support in the AMD RPU Legacy OpenAMP so that the RPU can have IPC reconnected if host has an uncontrolled reboot.
CC @tnmysh
=> Amd june30 recovery update

examples/legacy_apps/system/linux/machine/generic/platform_info.c
Fix following build warning introduced in PR #76:
system/linux/machine/generic/platform_info.c:546:3: warning: implicit declaration of function ‘system_suspend’ [-Wimplicit-function-declaration]
546 |   system_suspend();
|   ^~~~~~~~~~~~~~
=> examples: legacy_apps: Fix add default routines for suspend/resume
